# Changes here will be overwritten by Copier
_commit: v0.0.2-11-g28c380d
_src_path: https://github.com/UpDryTwist/stock-python-template.git
author_email: tathamg@gmail.com
author_name: UpDryTwist
docker_project: battery-hawk
project_description: Battery Hawk is to use BM* (starting with BM6) BLE battery monitors
    to monitor batteries in cars and boats, and integrate with alerts as appropriate.
project_name: Battery Hawk
project_slug: battery_hawk
python_package: battery_hawk
python_package_command_line_name: battery-hawk
python_version: '3.13'
repository_name: battery-hawk
