version: '3.8'

services:
  battery-hawk:
    build: .
    container_name: battery-hawk
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./local-instance/data:/data
      - ./local-instance/config:/config
      - ./local-instance/logs:/logs
      - /var/run/dbus:/var/run/dbus
    environment:
      - BATTERYHAWK_INFLUXDB_HOST=localhost
      - BATTERYHAWK_INFLUXDB_PORT=8086
      - BATTERYHAWK_INFLUXDB_DATABASE=battery_hawk
      - BATTERYHAWK_INFLUXDB_USERNAME=admin
      - BATTERYHAWK_INFLUXDB_PASSWORD=admin
      - BATTERYHAWK_LOGGING_LEVEL=INFO
      - BATTERYHAWK_API_PORT=5000
      - BATTERYHAWK_MQTT_BROKER=localhost
      - BATTERYHAWK_MQTT_PORT=1883
      - BATTERYHAWK_MQTT_TOPIC_PREFIX=battery_hawk
    depends_on:
      - influxdb
      - mqtt-broker
    command: ["python", "-m", "battery_hawk"]

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./local-instance/influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=battery_hawk
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./local-instance/mosquitto/config:/mosquitto/config
      - ./local-instance/mosquitto/data:/mosquitto/data
      - ./local-instance/mosquitto/log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  influxdb-data:
  mosquitto-data:
