# Production Docker Compose configuration for Battery Hawk
# This file extends the base docker-compose.yml with production-specific settings

services:
  battery-hawk:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      # Override development settings
      - BATTERYHAWK_SYSTEM_LOGGING_LEVEL=${LOG_LEVEL:-INFO}
      - BATTERYHAWK_SYSTEM_API_PORT=${API_PORT:-5000}
      - BATTERYHAWK_SYSTEM_INFLUXDB_HOST=${INFLUXDB_HOST:-influxdb}
      - BATTERYHAWK_SYSTEM_INFLUXDB_PORT=${INFLUXDB_PORT:-8086}
      - BATTERYHAWK_SYSTEM_INFLUXDB_DATABASE=${INFLUXDB_DATABASE:-battery_hawk}
      - BATTERYHAWK_SYSTEM_INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-admin}
      - BATTERYHAWK_SYSTEM_INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-admin}
      - BATTERYHAWK_SYSTEM_MQTT_BROKER=${MQTT_BROKER:-mqtt-broker}
      - BATTERYHAWK_SYSTEM_MQTT_PORT=${MQTT_PORT:-1883}
      - BATTERYHAWK_SYSTEM_MQTT_USERNAME=${MQTT_USERNAME:-}
      - BATTERYHAWK_SYSTEM_MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - BATTERYHAWK_SYSTEM_MQTT_TOPIC_PREFIX=${MQTT_TOPIC_PREFIX:-battery_hawk}
      - BATTERYHAWK_SYSTEM_MQTT_TLS=${MQTT_TLS:-false}
    volumes:
      # Use named volumes for production
      - battery_hawk_config:/config
      - battery_hawk_data:/data
      - battery_hawk_logs:/logs
      - /var/run/dbus:/var/run/dbus:ro
    security_opt:
      - no-new-privileges:true
    read_only: false  # Cannot be read-only due to BLE requirements
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-battery-hawk}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-battery_hawk}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION:-30d}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mqtt-broker:
    volumes:
      - mqtt_config:/mosquitto/config:ro
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=50m

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: battery-hawk-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_HOST_PORT:-80}:80"
      - "${NGINX_HTTPS_HOST_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - battery-hawk
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/run:noexec,nosuid,size=100m
      - /var/cache/nginx:noexec,nosuid,size=100m
      - /tmp:noexec,nosuid,size=50m
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  battery_hawk_config:
    driver: local
  battery_hawk_data:
    driver: local
  battery_hawk_logs:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  mqtt_config:
    driver: local
  mqtt_data:
    driver: local
  mqtt_logs:
    driver: local
  nginx_cache:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
