
services:
  battery-hawk:
    build: .
    container_name: battery-hawk
    restart: unless-stopped
    network_mode: host
    privileged: true  # Required for Bluetooth Low Energy access
    cap_add:
      - NET_ADMIN  # Required for BLE adapter control
      - SYS_ADMIN  # Required for BLE operations
    volumes:
      - ./local-instance/data:/data
      - ./local-instance/config:/config
      - ./local-instance/logs:/logs
      - /var/run/dbus:/var/run/dbus:ro  # Read-only access to D-Bus
    environment:
      - BATTERYHAWK_SYSTEM_INFLUXDB_HOST=localhost
      - BATTERYHAWK_SYSTEM_INFLUXDB_PORT=8086
      - BATTERYHAWK_SYSTEM_INFLUXDB_DATABASE=battery_hawk
      - BATTERYHAWK_SYSTEM_INFLUXDB_USERNAME=admin
      - BATTERYHAWK_SYSTEM_INFLUXDB_PASSWORD=admin
      - BATTERYHAWK_SYSTEM_LOGGING_LEVEL=INFO
      - BATTERYHAWK_SYSTEM_API_PORT=5000
      - BATTERYHAWK_SYSTEM_MQTT_BROKER=localhost
      - BATTERYHAWK_SYSTEM_MQTT_PORT=1883
      - BATTERYHAWK_SYSTEM_MQTT_TOPIC_PREFIX=battery_hawk
    depends_on:
      - influxdb
      - mqtt-broker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "${INFLUXDB_HOST_PORT:-8086}:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=battery_hawk
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'


  # --- Alternative InfluxDB 2.x service (commented) ---
  # influxdb:
  #   image: influxdb:2.7
  #   container_name: influxdb
  #   restart: unless-stopped
  #   ports:
  #     - "${INFLUXDB_HOST_PORT:-8086}:8086"
  #   volumes:
  #     - influxdb-data:/var/lib/influxdb2
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-changeme}
  #     - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-battery-hawk}
  #     - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-battery_hawk}
  #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-changeme}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "${MQTT_HOST_PORT:-1883}:1883"
      - "${MQTT_WEBSOCKET_HOST_PORT:-9001}:9001"
    volumes:
      - ./local-instance/mosquitto/config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - ./local-instance/mosquitto/log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "health", "-m", "test", "-q", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  influxdb-data:
  mosquitto-data:
